### PR TITLE
1.1 docsreadme

### PR DESCRIPTION
**Pull request by d1rk**
just fixing the links in the readme to new locations within documentation.

### CODE REVIEW

**Comment by davidpersson** [comment]
Thanks for spotting the link breakage. It seems some extra commits sneaked into this PR. We should probably add the redirects for the old links here https://github.com/UnionOfRAD/site/blob/master/app/config/routes.php too as there are probably more of these out there.

**Comment by d1rk** [comment]
i noticed the extra-commits but was not able to grasp how they've come into that. Is the branch i am pull-requesting against the correct one?

**Comment by davidpersson** [comment]
The 1.1 branch is the correct one. I guess you patch predates the latest 1.1 branch updates.

**Comment by davidpersson** [comment]
I'll cherry pick the commit from here.

**Comment by davidpersson** [comment]
Added as d99dfdfeb75f07fb41fa0e458cea89ebd0b7505e

**Pull request closed without merging**
